runmode: debug               # 开发模式 debug, release, test
addr: :7777                  # HTTP绑定端口
name: go-rest-demo           # API Server的名字
url: http://127.0.0.1:7777   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/rest-demo.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: rest
  addr: 127.0.0.1:3306
  username: root
  password: reddean
docker_db:
  name: rest
  addr: 127.0.0.1:3306
  username: root
  password: reddean